export const path = {
    HOME: '/',
    LOGIN: '/Login',
    PRODUCT: '/Prouduct',
    LAPTOP: '/Categories/Laptop',
    SMARTPHONE: '/Categories/SmartPhone',
    TABLET: '/Categories/Tablet',
    PRODUCTDETAILS: '/ProductDetails/:slug',
    CART: '/Cart',
    REGISTER: '/Register',
    FORGOTPASSWORD: '/ForgotPassword',
    USERPROFILE: '/UserProfile',
    USERPURECHASED: '/UserProfile/Purchased',
    USERADDRESS: '/UserProfile/Address',
    USERCHANGEPASS: '/UserProfile/ChangePassword',
}